classdef GetHoldingStatusResponse < ros.Message
    %GetHoldingStatusResponse MATLAB implementation of rv_msgs/GetHoldingStatusResponse
    %   This class was automatically generated by
    %   ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'rv_msgs/GetHoldingStatusResponse' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '9ee0c3b51da996f6235861e8703b899f' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        IsHolding
        WeightHeld
    end
    
    properties (Constant, Hidden)
        PropertyList = {'IsHolding', 'WeightHeld'} % List of non-constant message properties
        ROSPropertyList = {'is_holding', 'weight_held'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = GetHoldingStatusResponse(msg)
            %GetHoldingStatusResponse Construct the message object GetHoldingStatusResponse
            import com.mathworks.toolbox.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('ros:mlros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('ros:mlros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('ros:mlros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function isholding = get.IsHolding(obj)
            %get.IsHolding Get the value for property IsHolding
            isholding = logical(obj.JavaMessage.getIsHolding);
        end
        
        function set.IsHolding(obj, isholding)
            %set.IsHolding Set the value for property IsHolding
            validateattributes(isholding, {'logical', 'numeric'}, {'nonempty', 'scalar'}, 'GetHoldingStatusResponse', 'IsHolding');
            
            obj.JavaMessage.setIsHolding(isholding);
        end
        
        function weightheld = get.WeightHeld(obj)
            %get.WeightHeld Get the value for property WeightHeld
            weightheld = single(obj.JavaMessage.getWeightHeld);
        end
        
        function set.WeightHeld(obj, weightheld)
            %set.WeightHeld Set the value for property WeightHeld
            validateattributes(weightheld, {'numeric'}, {'nonempty', 'scalar'}, 'GetHoldingStatusResponse', 'WeightHeld');
            
            obj.JavaMessage.setWeightHeld(weightheld);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.IsHolding = obj.IsHolding;
            cpObj.WeightHeld = obj.WeightHeld;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.IsHolding = strObj.IsHolding;
            obj.WeightHeld = strObj.WeightHeld;
        end
    end
    
    methods (Access = ?ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.IsHolding = obj.IsHolding;
            strObj.WeightHeld = obj.WeightHeld;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.custom.msggen.rv_msgs.GetHoldingStatusResponse.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = ros.custom.msggen.rv_msgs.GetHoldingStatusResponse;
            obj.reload(strObj);
        end
    end
end
