classdef ListenGoal < ros.Message
    %ListenGoal MATLAB implementation of rv_msgs/ListenGoal
    %   This class was automatically generated by
    %   ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'rv_msgs/ListenGoal' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '6f211bebbe849d78faf6a260c9074c60' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        TimeoutSeconds
        WaitForWake
    end
    
    properties (Constant, Hidden)
        PropertyList = {'TimeoutSeconds', 'WaitForWake'} % List of non-constant message properties
        ROSPropertyList = {'timeout_seconds', 'wait_for_wake'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = ListenGoal(msg)
            %ListenGoal Construct the message object ListenGoal
            import com.mathworks.toolbox.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('ros:mlros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('ros:mlros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('ros:mlros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function timeoutseconds = get.TimeoutSeconds(obj)
            %get.TimeoutSeconds Get the value for property TimeoutSeconds
            timeoutseconds = single(obj.JavaMessage.getTimeoutSeconds);
        end
        
        function set.TimeoutSeconds(obj, timeoutseconds)
            %set.TimeoutSeconds Set the value for property TimeoutSeconds
            validateattributes(timeoutseconds, {'numeric'}, {'nonempty', 'scalar'}, 'ListenGoal', 'TimeoutSeconds');
            
            obj.JavaMessage.setTimeoutSeconds(timeoutseconds);
        end
        
        function waitforwake = get.WaitForWake(obj)
            %get.WaitForWake Get the value for property WaitForWake
            waitforwake = logical(obj.JavaMessage.getWaitForWake);
        end
        
        function set.WaitForWake(obj, waitforwake)
            %set.WaitForWake Set the value for property WaitForWake
            validateattributes(waitforwake, {'logical', 'numeric'}, {'nonempty', 'scalar'}, 'ListenGoal', 'WaitForWake');
            
            obj.JavaMessage.setWaitForWake(waitforwake);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.TimeoutSeconds = obj.TimeoutSeconds;
            cpObj.WaitForWake = obj.WaitForWake;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.TimeoutSeconds = strObj.TimeoutSeconds;
            obj.WaitForWake = strObj.WaitForWake;
        end
    end
    
    methods (Access = ?ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.TimeoutSeconds = obj.TimeoutSeconds;
            strObj.WaitForWake = obj.WaitForWake;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.custom.msggen.rv_msgs.ListenGoal.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = ros.custom.msggen.rv_msgs.ListenGoal;
            obj.reload(strObj);
        end
    end
end
