classdef ParseIntentResponse < ros.Message
    %ParseIntentResponse MATLAB implementation of rv_msgs/ParseIntentResponse
    %   This class was automatically generated by
    %   ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'rv_msgs/ParseIntentResponse' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '2a0399c053c5782ed14b49d7e9d9b7a3' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        IntentAnswer
        IntentJson
    end
    
    properties (Constant, Hidden)
        PropertyList = {'IntentAnswer', 'IntentJson'} % List of non-constant message properties
        ROSPropertyList = {'intent_answer', 'intent_json'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = ParseIntentResponse(msg)
            %ParseIntentResponse Construct the message object ParseIntentResponse
            import com.mathworks.toolbox.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('ros:mlros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('ros:mlros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('ros:mlros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function intentanswer = get.IntentAnswer(obj)
            %get.IntentAnswer Get the value for property IntentAnswer
            intentanswer = char(obj.JavaMessage.getIntentAnswer);
        end
        
        function set.IntentAnswer(obj, intentanswer)
            %set.IntentAnswer Set the value for property IntentAnswer
            intentanswer = convertStringsToChars(intentanswer);
            
            validateattributes(intentanswer, {'char', 'string'}, {}, 'ParseIntentResponse', 'IntentAnswer');
            
            obj.JavaMessage.setIntentAnswer(intentanswer);
        end
        
        function intentjson = get.IntentJson(obj)
            %get.IntentJson Get the value for property IntentJson
            intentjson = char(obj.JavaMessage.getIntentJson);
        end
        
        function set.IntentJson(obj, intentjson)
            %set.IntentJson Set the value for property IntentJson
            intentjson = convertStringsToChars(intentjson);
            
            validateattributes(intentjson, {'char', 'string'}, {}, 'ParseIntentResponse', 'IntentJson');
            
            obj.JavaMessage.setIntentJson(intentjson);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.IntentAnswer = obj.IntentAnswer;
            cpObj.IntentJson = obj.IntentJson;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.IntentAnswer = strObj.IntentAnswer;
            obj.IntentJson = strObj.IntentJson;
        end
    end
    
    methods (Access = ?ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.IntentAnswer = obj.IntentAnswer;
            strObj.IntentJson = obj.IntentJson;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.custom.msggen.rv_msgs.ParseIntentResponse.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = ros.custom.msggen.rv_msgs.ParseIntentResponse;
            obj.reload(strObj);
        end
    end
end
