classdef ProcessObservationRequest < ros.Message
    %ProcessObservationRequest MATLAB implementation of rv_msgs/ProcessObservationRequest
    %   This class was automatically generated by
    %   ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'rv_msgs/ProcessObservationRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'e68599afa630fcdf55a202d02bde7cac' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        RvMsgsObservationClass = ros.msg.internal.MessageFactory.getClassForType('rv_msgs/Observation') % Dispatch to MATLAB class for message type rv_msgs/Observation
    end
    
    properties (Dependent)
        Observation
    end
    
    properties (Access = protected)
        Cache = struct('Observation', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Observation'} % List of non-constant message properties
        ROSPropertyList = {'observation'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = ProcessObservationRequest(msg)
            %ProcessObservationRequest Construct the message object ProcessObservationRequest
            import com.mathworks.toolbox.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('ros:mlros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('ros:mlros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('ros:mlros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function observation = get.Observation(obj)
            %get.Observation Get the value for property Observation
            if isempty(obj.Cache.Observation)
                obj.Cache.Observation = feval(obj.RvMsgsObservationClass, obj.JavaMessage.getObservation);
            end
            observation = obj.Cache.Observation;
        end
        
        function set.Observation(obj, observation)
            %set.Observation Set the value for property Observation
            validateattributes(observation, {obj.RvMsgsObservationClass}, {'nonempty', 'scalar'}, 'ProcessObservationRequest', 'Observation');
            
            obj.JavaMessage.setObservation(observation.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Observation)
                obj.Cache.Observation.setJavaObject(observation.getJavaObject);
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Observation = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.Observation = copy(obj.Observation);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Observation = feval([obj.RvMsgsObservationClass '.loadobj'], strObj.Observation);
        end
    end
    
    methods (Access = ?ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Observation = saveobj(obj.Observation);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.custom.msggen.rv_msgs.ProcessObservationRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = ros.custom.msggen.rv_msgs.ProcessObservationRequest;
            obj.reload(strObj);
        end
    end
end
