classdef SaveFaceRequest < ros.Message
    %SaveFaceRequest MATLAB implementation of rv_msgs/SaveFaceRequest
    %   This class was automatically generated by
    %   ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'rv_msgs/SaveFaceRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '1062b9e761d3e9d0147ae3d1f8fe212e' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        RvMsgsDetectionClass = ros.msg.internal.MessageFactory.getClassForType('rv_msgs/Detection') % Dispatch to MATLAB class for message type rv_msgs/Detection
    end
    
    properties (Dependent)
        Face
    end
    
    properties (Access = protected)
        Cache = struct('Face', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Face'} % List of non-constant message properties
        ROSPropertyList = {'face'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = SaveFaceRequest(msg)
            %SaveFaceRequest Construct the message object SaveFaceRequest
            import com.mathworks.toolbox.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('ros:mlros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('ros:mlros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('ros:mlros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function face = get.Face(obj)
            %get.Face Get the value for property Face
            if isempty(obj.Cache.Face)
                obj.Cache.Face = feval(obj.RvMsgsDetectionClass, obj.JavaMessage.getFace);
            end
            face = obj.Cache.Face;
        end
        
        function set.Face(obj, face)
            %set.Face Set the value for property Face
            validateattributes(face, {obj.RvMsgsDetectionClass}, {'nonempty', 'scalar'}, 'SaveFaceRequest', 'Face');
            
            obj.JavaMessage.setFace(face.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Face)
                obj.Cache.Face.setJavaObject(face.getJavaObject);
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Face = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.Face = copy(obj.Face);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Face = feval([obj.RvMsgsDetectionClass '.loadobj'], strObj.Face);
        end
    end
    
    methods (Access = ?ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Face = saveobj(obj.Face);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.custom.msggen.rv_msgs.SaveFaceRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = ros.custom.msggen.rv_msgs.SaveFaceRequest;
            obj.reload(strObj);
        end
    end
end
