classdef SetNamedPoseRequest < ros.Message
    %SetNamedPoseRequest MATLAB implementation of rv_msgs/SetNamedPoseRequest
    %   This class was automatically generated by
    %   ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'rv_msgs/SetNamedPoseRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '1a42a4f7dc2f5f4e8c5c76c06e7be3ed' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        PoseName
        Overwrite
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Overwrite', 'PoseName'} % List of non-constant message properties
        ROSPropertyList = {'overwrite', 'pose_name'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = SetNamedPoseRequest(msg)
            %SetNamedPoseRequest Construct the message object SetNamedPoseRequest
            import com.mathworks.toolbox.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('ros:mlros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('ros:mlros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('ros:mlros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function posename = get.PoseName(obj)
            %get.PoseName Get the value for property PoseName
            posename = char(obj.JavaMessage.getPoseName);
        end
        
        function set.PoseName(obj, posename)
            %set.PoseName Set the value for property PoseName
            posename = convertStringsToChars(posename);
            
            validateattributes(posename, {'char', 'string'}, {}, 'SetNamedPoseRequest', 'PoseName');
            
            obj.JavaMessage.setPoseName(posename);
        end
        
        function overwrite = get.Overwrite(obj)
            %get.Overwrite Get the value for property Overwrite
            overwrite = logical(obj.JavaMessage.getOverwrite);
        end
        
        function set.Overwrite(obj, overwrite)
            %set.Overwrite Set the value for property Overwrite
            validateattributes(overwrite, {'logical', 'numeric'}, {'nonempty', 'scalar'}, 'SetNamedPoseRequest', 'Overwrite');
            
            obj.JavaMessage.setOverwrite(overwrite);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.PoseName = obj.PoseName;
            cpObj.Overwrite = obj.Overwrite;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.PoseName = strObj.PoseName;
            obj.Overwrite = strObj.Overwrite;
        end
    end
    
    methods (Access = ?ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.PoseName = obj.PoseName;
            strObj.Overwrite = obj.Overwrite;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.custom.msggen.rv_msgs.SetNamedPoseRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = ros.custom.msggen.rv_msgs.SetNamedPoseRequest;
            obj.reload(strObj);
        end
    end
end
