# Goal definition
int8 MODE_STATIC=0
int8 MODE_GRASP=1

int8 STATE_CLOSED=0
int8 STATE_OPEN=1

## Grasp control mode
int8 mode

## Grasp control mode inputs
int8 state
float64 width

## Grasp parameters
float64 force
float64 speed

## Tolerance
float64 e_inner
float64 e_outer

---
# Result definition
int32 result
---
# Feedback definition
float64 feedback
float64[] data
